# Copyright (c) HashiCorp, Inc.

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/tfc-agent:latest",
        "-t",
        "gcr.io/$PROJECT_ID/tfc-agent:0.1",
        ".",
      ]
images:
  - "gcr.io/$PROJECT_ID/tfc-agent"
