# Copyright (c) HashiCorp, Inc.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sample-manifests/deployment.yaml
- sample-manifests/hpa.yaml
images:
- name: gcr.io/PROJECT_ID/tfc-agent:latest
  newName: gcr.io/PROJECT_ID/tfc-agent
  newTag: latest
